* 总体印象：
** 这是一本什么书？
   不用读完全文就可以知道，这是一本读书笔记，记述了作者阅读了芒格,巴菲特等相关书籍后的心得体会。芒格一生，多以演讲为多，很少著述，讲演中提到的很多方法也很少提如何去应用。本书作者系统的梳理了芒格提出的多维思维方法，列举了大量实例来说明用法，是解读芒格思想的一把非常好的钥匙。
   本书可以说是读书笔记范文。有时读完一本书后，不知道如何去记笔记，通常的做法是用思维导图把各个章节摘录一下，那和书的目录有什么区别？读书笔记最重要的，是用自己的语言复述书中的观点，本书完美的诠释了这一点。

** 书中的主要观点
     书的观点主要来自芒格，特别是多维思考方式。芒格提到，我们应该吸取各学科的基本思想，来帮助我们思维。各学科的基本思想，对我们比较有用的是物理学的临界值理论，和数学的概率思想。

   临界值理论，要特别关注事情在极端情况下的反应，事物在极端情况下的反应，通常和平常不太一样。
   
   要多用概率思想来帮助我们有效决策和规划。
   现代心理学的思想，对我们认识自己的大脑，从而更清晰的思维很有帮助。特别要关注，人类思想有很多思维误区，会让人产生错误的决策和判断。
   
** 组织
   基于这样的思路,全书共分为4个部分，第一部分讲大脑受什么影响，第二部分讲常见的心理误判，第三部分讲物理和数学的误判，第四部分讲如何更好的思考。
   
* 第一部分：大脑受什么影响
  最新的心理学研究表明，人脑的很多机制，是在长期进化过程中形成的，比如，人脑往往喜欢走捷径，快速决策。在远古恶劣环境下，人需要快速决策，才能生存下来，可以想象一下，在野外面对一头狼时，理性显然不如本能反应更重要。
  从众心理也是人的本能需要，在恶劣环境下，个体生存的概率肯定小于群体的概率，个体会千方百计加入某个团队，团队能给人带来极大的安全感。群体思维压倒个体思维，人宁可放弃自己的个体思维，也要融入群体中。

** 思考方式
   人的思考方式主要是模式识别，人依赖于以前的经验和文化对我们的影响。正因为经验如此重要，专家和新手的区别就在于专家有足够多的经验积累，专家可以从以前的经验中形成很多模式，在后续的决策时从以前的模式中识别出有用的信息。要成为某个领域的专家，持续的学习和总结很重要。
   
* 第二部分：心理误判
  芒格给我们列出了一个长长的清单，并建议我们思考问题前逐个去考虑清单中的因素。有一本讲原则的书中，也提到了，人应该根据自己的情况，形成自己的原则清单，把每个概念都弄清楚，《原则》那本书中的清单有200~300个之多。

  这么长的书单，我们如何能一一把它记住呢？靠记忆肯定是不可能的，只能靠运用了。
  下面挑选感觉印象比较深刻的几点，记录一下，也是《影响力》这本书中重点介绍的。

** 奖惩机制
   奖励和惩罚可能是对人来说经常会碰到，可以说是最重要的机制了，没有之一。有人说，如果用经量少的字来概括心理学，那就是反馈和奖励，人脑随时在需求各种正反馈。如果一个人做错了事情，那么激励带来的效果，要远大于批评。批评只会产生负面效果，不会有任何激励作用。有时人比较天真，以为批评可以让人产生向前的压力和动力。

** 承诺和一致性
   这也是人的天性之一，最有效的运用是推销员推销东西时，希望购买者主动承诺，这样购买的概率就会高很多。在团队中，主动认领任务也相当于是做出某种承诺，承诺后一般人就会努力去完成。

** 社会认同
   在团队管理中，可以利用同伴压力去驱动大家一起进步。在一个优秀的团队中，不优秀甚至次优秀的都会产生巨大的压力，因此，打造一个优秀的团队，让优秀人的成就秀出来，就会对其他人产生驱动力。同样，在一个不优秀的团队中，个别优秀的人也是待不住的，有时会出现劣币驱良币效应。

** 寻找理性
   人总是喜欢寻找理由，地球围绕太阳转，还是太阳围绕地球转，为什么会这样。人是理性的吗？也许是，也许不是。有些人相信一切都是理性的，一切都可以循着某条逻辑推导出结论。但是，千万不要忽略一些异常，即所谓的黑天鹅事件，黑天鹅事件用理性是无法解释的。

** 小结
   清单很长，第三遍记笔记时发现，除了在《影响力》，或其他书中读过的观点，其他大部分都已经忘却了。人的大脑确实容易健忘，采用主题阅读方法，大量的阅读同一主题的书籍，可以相互参照，印象会比较深刻。

* 第三部分 物理和数学的基本原则

** 系统思维
   系统思维的核心是多角度思考，知易行难，说起来很简单，多方位思考，具体操作时，还是不知道如何下手。思考什么？思考动作带来的后果，任何动作都有后果。
